### ISSUE TITLE
Code is hard to read because of colors

### ISSUE THREAD

**Issue by etiennebacher** [jonocarroll/jcarroll.com.au#36]
Hi, I like your blog, you have some very nice posts!

However the background and text colors make it hard to read the code. This happens in both light and dark mode, is it possible to update them?

Light mode:

![image](https://github.com/jonocarroll/jcarroll.com.au/assets/52219252/67bae359-f711-4fa1-bf9e-c9104204384b)

Dark mode:

![image](https://github.com/jonocarroll/jcarroll.com.au/assets/52219252/a841f339-d0f9-479e-bcd8-29914dcecc12)

If it helps I'm using Firefox 115.

Thank you!

**Comment by jonocarroll** [comment]
Yes, it's due to this https://github.com/halogenica/beautifulhugo/issues/459

If you switch your system theme to light then my switch works, but otherwise it seems to have no effect.

I'm planning to try overwriting the prefers-dark CSS but I'm not 100% sure how.

**Comment by etiennebacher** [comment]
Alright, then I'll use this workaround for now

**Comment by jonocarroll** [comment]
I've just pushed a change that might help... Please let me know if it does/doesn't.

**Comment by etiennebacher** [comment]
Almost there, the code blocks are good now but the inline code has a very light color (in both modes):

![image](https://github.com/jonocarroll/jcarroll.com.au/assets/52219252/3e140ece-e8c7-4866-8029-960b037c4e4c)

**Comment by jonocarroll** [comment]
Yep, I just made one more push - I noticed that too late.

**Comment by etiennebacher** [comment]
All good now, thank you
